### ISSUE TITLE
Problem running the demos themselves

### ISSUE THREAD

**Issue by RX-00** [machines-in-motion/reactive_planners#15] opened 2021-11-28 04:02 UTC
Hello! I'm trying to run the demos for the bolt biped robot and the solo12 quadruped but I am running into some strange issues (this is all done on a freshly nuked and re-installed computer with Ubuntu 20.04).

here is my output for when I build with: `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`

> Starting >>> googletest-distribution
Starting >>> mpi_cmake_modules
Starting >>> pybind11
Finished <<< mpi_cmake_modules [0.24s]                                           
Starting >>> bullet_utils
Finished <<< pybind11 [0.66s]                                                     
Finished <<< googletest-distribution [0.72s]                                                     
Starting >>> yaml_utils
Starting >>> real_time_tools
Finished <<< yaml_utils [0.24s]                                                            
Finished <<< real_time_tools [0.43s]                                                        
Starting >>> reactive_planners
Finished <<< reactive_planners [0.38s]                                                        
--- stderr: bullet_utils                    
pybullet build time: Oct 11 2021 20:59:39
/home/roy/.local/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/roy/odri_dev/workspace/build/bullet_utils/build/lib/bullet_utils/doc/readme.md: WARNING: document isn't included in any toctree
---
>Finished <<< bullet_utils [2.92s]
Starting >>> robot_properties_bolt
Starting >>> robot_properties_solo                   
resources =  ['resources/impedance_ctrl.yaml', 'resources/dynamic_graph_manager/dgm_parameters_bolt.yaml', 'resources/odri_control_interface/bolt_driver.yaml', 'resources/__pycache__/__init__.cpython-38.pyc', 'resources/xacro/bolt_passive_ankle.urdf.xacro', 'resources/xacro/bolt.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/bolt.xacro', 'resources/xacro/leg.xacro', 'resources/meshes/checker_blue.png', 'resources/meshes/plane.obj', 'resources/meshes/plane.mtl', 'resources/meshes/obj/bolt_upper_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_left_side.obj', 'resources/meshes/obj/bolt_upper_leg_left_side.obj', 'resources/meshes/obj/bolt_lower_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_right_side.obj', 'resources/meshes/obj/bolt_body.obj', 'resources/meshes/obj/bolt_foot.obj', 'resources/meshes/obj/bolt_lower_leg_left_side.obj', 'resources/meshes/stl/lower_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_upper_leg_left_side.stl', 'resources/meshes/stl/upper_leg_200mm_right_side.stl', 'resources/meshes/stl/upper_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_hip_fe_right_side.stl', 'resources/meshes/stl/bolt_lower_leg_left_side.stl', 'resources/meshes/stl/bolt_foot.stl', 'resources/meshes/stl/lower_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_hip_fe_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_right_side.stl', 'resources/meshes/stl/bolt_upper_leg_right_side.stl', 'resources/meshes/stl/bolt_body.stl']
resources =  ['resources/impedance_ctrl.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_wireless_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_nyu.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8ti.yaml', 'resources/odri_control_interface/solo12_driver.yaml', 'resources/launch/visual_rviz.launch', 'resources/launch/dashboard.launch', 'resources/launch/bringup.launch', 'resources/launch/rviz.launch', 'resources/rviz/display.rviz', 'resources/rviz/solo.rviz', 'resources/rviz/dgbullet_vs_pybullet.rviz', 'resources/__pycache__/__init__.cpython-38.pyc', 'resources/srdf/solo.srdf', 'resources/pre_generated_urdf/readme.md', 'resources/xacro/solo8.urdf.xacro', 'resources/xacro/solo12.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/rqt/solo.perspective.in', 'resources/meshes/cylinder.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/cube.obj', 'resources/meshes/plane.obj', 'resources/meshes/sphere.obj', 'resources/meshes/plane.mtl', 'resources/meshes/obj/without_foot/solo_body.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_body.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_body.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_foot.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.mtl', 'resources/meshes/obj/with_foot/solo_body.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.obj', 'resources/meshes/stl/without_foot/solo_body.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_left_side.stl', 'resources/meshes/stl/solo12/_solo12_visualisation_model.PDF', 'resources/meshes/stl/solo12/solo_12_base.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hl.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_fr.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_fl.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hr.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_4.png', 'resources/meshes/stl/solo12/solo12_lower_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_2.png', 'resources/meshes/stl/solo12/solo12_coordinate_systems.png', 'resources/meshes/stl/solo12/solo12_coordinate_systems_3.png', 'resources/meshes/stl/with_foot/solo_body.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_foot.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_right_side.stl']
--- stderr: robot_properties_bolt                                                               
resources =  ['resources/impedance_ctrl.yaml', 'resources/dynamic_graph_manager/dgm_parameters_bolt.yaml', 'resources/odri_control_interface/bolt_driver.yaml', 'resources/__pycache__/__init__.cpython-38.pyc', 'resources/xacro/bolt_passive_ankle.urdf.xacro', 'resources/xacro/bolt.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/bolt.xacro', 'resources/xacro/leg.xacro', 'resources/meshes/checker_blue.png', 'resources/meshes/plane.obj', 'resources/meshes/plane.mtl', 'resources/meshes/obj/bolt_upper_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_left_side.obj', 'resources/meshes/obj/bolt_upper_leg_left_side.obj', 'resources/meshes/obj/bolt_lower_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_right_side.obj', 'resources/meshes/obj/bolt_body.obj', 'resources/meshes/obj/bolt_foot.obj', 'resources/meshes/obj/bolt_lower_leg_left_side.obj', 'resources/meshes/stl/lower_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_upper_leg_left_side.stl', 'resources/meshes/stl/upper_leg_200mm_right_side.stl', 'resources/meshes/stl/upper_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_hip_fe_right_side.stl', 'resources/meshes/stl/bolt_lower_leg_left_side.stl', 'resources/meshes/stl/bolt_foot.stl', 'resources/meshes/stl/lower_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_hip_fe_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_right_side.stl', 'resources/meshes/stl/bolt_upper_leg_right_side.stl', 'resources/meshes/stl/bolt_body.stl']
/home/roy/.local/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
pybullet build time: Oct 11 2021 20:59:39
WARNING: autodoc: failed to import module 'bolt_wrapper' from module 'robot_properties_bolt'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_bolt.resources' (/home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/__init__.py)
WARNING: autodoc: failed to import module 'config' from module 'robot_properties_bolt'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_bolt.resources' (/home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/__init__.py)
WARNING: autodoc: failed to import module 'gepetto_gui_loader' from module 'robot_properties_bolt'; the following exception was raised:
No module named 'config'
/home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/__init__.py:docstring of robot_properties_bolt.resources:1: WARNING: duplicate object description of robot_properties_bolt.resources, other instance in robot_properties_bolt, use :noindex: for one of them
/home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/doc/readme.md: WARNING: document isn't included in any toctree
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
---
>Finished <<< robot_properties_bolt [3.32s]
--- stderr: robot_properties_solo                    
resources =  ['resources/impedance_ctrl.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_wireless_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_nyu.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8ti.yaml', 'resources/odri_control_interface/solo12_driver.yaml', 'resources/launch/visual_rviz.launch', 'resources/launch/dashboard.launch', 'resources/launch/bringup.launch', 'resources/launch/rviz.launch', 'resources/rviz/display.rviz', 'resources/rviz/solo.rviz', 'resources/rviz/dgbullet_vs_pybullet.rviz', 'resources/__pycache__/__init__.cpython-38.pyc', 'resources/srdf/solo.srdf', 'resources/pre_generated_urdf/readme.md', 'resources/xacro/solo8.urdf.xacro', 'resources/xacro/solo12.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/rqt/solo.perspective.in', 'resources/meshes/cylinder.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/cube.obj', 'resources/meshes/plane.obj', 'resources/meshes/sphere.obj', 'resources/meshes/plane.mtl', 'resources/meshes/obj/without_foot/solo_body.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_body.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_body.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_foot.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.mtl', 'resources/meshes/obj/with_foot/solo_body.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.obj', 'resources/meshes/stl/without_foot/solo_body.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_left_side.stl', 'resources/meshes/stl/solo12/_solo12_visualisation_model.PDF', 'resources/meshes/stl/solo12/solo_12_base.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hl.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_fr.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_fl.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hr.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_4.png', 'resources/meshes/stl/solo12/solo12_lower_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_2.png', 'resources/meshes/stl/solo12/solo12_coordinate_systems.png', 'resources/meshes/stl/solo12/solo12_coordinate_systems_3.png', 'resources/meshes/stl/with_foot/solo_body.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_foot.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_right_side.stl']
/home/roy/.local/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
pybullet build time: Oct 11 2021 20:59:39
WARNING: autodoc: failed to import module 'config' from module 'robot_properties_solo'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_solo.resources' (/home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/__init__.py)
WARNING: autodoc: failed to import module 'gepetto_gui_loader' from module 'robot_properties_solo'; the following exception was raised:
No module named 'config'
WARNING: autodoc: failed to import module 'quadruped12wrapper' from module 'robot_properties_solo'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_solo.resources' (/home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/__init__.py)
WARNING: autodoc: failed to import module 'solo12wrapper' from module 'robot_properties_solo'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_solo.resources' (/home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/__init__.py)
WARNING: autodoc: failed to import module 'solo8wrapper' from module 'robot_properties_solo'; the following exception was raised:
cannot import name 'Resources' from 'robot_properties_solo.resources' (/home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/__init__.py)
/home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/__init__.py:docstring of robot_properties_solo.resources:1: WARNING: duplicate object description of robot_properties_solo.resources, other instance in robot_properties_solo, use :noindex: for one of them
/home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/doc/readme.md: WARNING: document isn't included in any toctree
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
building xacro file ( /home/roy/odri_dev/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/roy/odri_dev/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
---
> Finished <<< robot_properties_solo [3.45s]
Starting >>> mim_control
Finished <<< mim_control [0.36s]                      

>Summary: 10 packages finished [7.73s]
  3 packages had stderr output: bullet_utils robot_properties_bolt robot_properties_solo

I then source with `source install/setup.bash` with no output results.

Finally I run `python3 src/reactive_planners/demos/demo_reactive_planners_bolt_step_adjustment.py` and I encounter this error that I'm stuck on:
> pybullet build time: Oct 11 2021 20:59:39
/opt/openrobots/lib/python3.8/site-packages/pinocchio/shortcuts.py:45: UserWarning: You passed package dir(s) via argument geometry_model and provided package_dirs.
  geom_model = pin.buildGeomFromUrdf(model, filename, geometry_type, package_dirs)
Traceback (most recent call last):
  File "src/reactive_planners/demos/demo_reactive_planners_bolt_step_adjustment.py", line 15, in <module>
    from reactive_planners_cpp import DcmReactiveStepper
ImportError: /home/roy/odri_dev/workspace/install/reactive_planners/lib/libreactive_planners.so: undefined symbol: _ZN5Eigen13QuadProgDense5solveERKNS_3RefIKNS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEELi0ENS_11OuterStrideILin1EEEEERKNS1_IKNS2_IdLin1ELi1ELi0ELin1ELi1EEELi0ENS_11InnerStrideILi1EEEEES9_SG_S9_SG_b

Regarding this error I have no clue left as to what to do next. Thank you so much for your time and help!

**Comment by Lhumd** [comment] 2021-12-24 14:18
Hello,
Sorry for my late response. Could you share with us which commit of each repository you are using?
Currently, reactive_planner doesn't support Ubuntu 20, but we are working on it.

**Comment by RX-00** [comment] 2022-01-12 21:28
Hello! No worries about the late response, I myself am also giving a late response after the winter holidays :) Hope you guys had a good break!

As for the commit of each repository:

For reactive_planner:
> commit d6d72a71ab6d71836eb5700b81f7071fac668ec5 (HEAD -> master, origin/master, origin/HEAD)
Author: majidkhadiv <48758317+majidkhadiv@users.noreply.github.com>
Date:   Fri Sep 24 12:00:35 2021 +0200

For robot_properties_bolt

> commit 8f5ecca8b91ca5c3596716b9162e8da36e8df823 (HEAD -> master, origin/master, origin/HEAD)
Author: Elham Daneshmand <elham.daneshmand@yahoo.com>
Date:   Sun Aug 29 15:21:36 2021 +0200


For the near future would you recommend trying reactive_planner only on an Ubuntu 18 machine? Thank you very much!

**Comment by RX-00** [comment] 2022-01-16 02:32
Ok, so I'm not sure what the heck happened, but I recompiled the workspace today and suddenly everything worked! Not sure why though, were there some changes recently pushed to apt relating to robotpkg? That's the only change I can think of.

**Comment by Lhumd** [comment] 2022-01-16 20:45
Great. So, I close this issue because the problem is solved.
Currently, reactive_planner is only tested on Ubuntu 18.

**Closed as completed by Lhumd** 2022-01-16 20:45 UTC

**Comment by RX-00** [comment] 2022-01-18 16:33
I would also like to make a quick note for future people. I was able to get reactive_planner to work on another laptop that was a fresh Ubuntu 20 installation too. So it's definitely possible, but as @Lhumd said be careful!

Thanks :)
